### ISSUE TITLE
getApps() or getSortedApps() not updating after installing/unistalling apps

### ISSUE THREAD

**Issue by toketas** [louaySleman/react-native-launcher-kit#4]
First of all thank you for this helpful and simple library! I would like to help improve it for sure!

For example, I have the current list of apps: `[1,2,3,4,5]`

When I install a new app (lets say 6) or if I delete one (example 4), the array doesnt get updated when I call `getApps()` again. I have to close/clear everything to do it.

**Comment by xiaozhang0532** [comment]
@toketas are you found the solution ?

**Comment by toketas** [comment]
> @toketas are you found the solution ?

I had to implement my own Native Module [here](https://github.com/toketas/rn-launcher/tree/main/android/app/src/main/java/com/toketas/simplelauncher)

**Comment by xiaozhang0532** [comment]
> > @toketas are you found the solution ?
> 
> I had to implement my own Native Module [here](https://github.com/toketas/rn-launcher/tree/main/android/app/src/main/java/com/toketas/simplelauncher)

got it, thanks bro

**Comment by louaySleman** [comment]
I'm currently working on a new update will fix this issue I'll let you know when it's up here @xiaozhang0532 @toketas

**Comment by 418442040** [comment]
I've also encountered this. Is there any solution currently? Unfortunately, I don't know Android native skills

**Comment by 418442040** [comment]
> > > @toketas你找到解决方案了吗？
> > 
> > 
> > 我必须[在这里实现我自己的本机模块](https://github.com/toketas/rn-launcher/tree/main/android/app/src/main/java/com/toketas/simplelauncher)
> 
> 明白了，谢谢老哥

哥们,怎么使用你修改过后的包呢?挺急的,谢谢

**Comment by 418442040** [comment]
> > > @toketas你找到解决方案了吗？
> > 
> > 
> > 我必须[在这里实现我自己的本机模块](https://github.com/toketas/rn-launcher/tree/main/android/app/src/main/java/com/toketas/simplelauncher)
> 
> 明白了，谢谢老哥

哥们,怎么使用你修改过后的包呢?挺急的,谢谢

**Comment by xiaozhang0532** [comment]
> > > > @toketas你找到解决方案了吗？
> > > 
> > > 
> > > 我必须[在这里实现我自己的本机模块](https://github.com/toketas/rn-launcher/tree/main/android/app/src/main/java/com/toketas/simplelauncher)
> > 
> > 
> > 明白了，谢谢老哥
> 
> 哥们,怎么使用你修改过后的包呢?挺急的,谢谢

你是指哪一个包

**Comment by SudhaRatan** [comment]
Hi, any update on this?

**Comment by louaySleman** [comment]
I apologize for the delay in addressing this issue. A new version has been developed, and while it has resolved the problem, it still requires some testing before being fully deployed. If you're okay with this, I can proceed with publishing it. The update also includes several new features that I believe you'll find valuable.
Please let me know your thoughts.
Wishing you all a great day!
@toketas @418442040 @SudhaRatan @xiaozhang0532

**Comment by louaySleman** [comment]
Fixed in v2.0.0! 🚀 

I apologize for the delayed response - work has been quite demanding lately. I'm happy to announce that going forward, this project will receive my full attention and support. Stay tuned for more regular updates and improvements!

**Comment by toketas** [comment]
> Fixed in v2.0.0! 🚀
> 
> I apologize for the delayed response - work has been quite demanding lately. I'm happy to announce that going forward, this project will receive my full attention and support. Stay tuned for more regular updates and improvements!

Thanks man, I will definitely try it!
