### ISSUE TITLE
Is it possible to use this package on iOS?

### ISSUE THREAD

**Issue by misharexviashvili** [louaySleman/react-native-launcher-kit#5]
This package works fine on android, it returns array of apps that are installed on android, but when I try to do same on iOS I get error:
<img width="674" alt="Screenshot 2024-03-06 at 19 43 59" src="https://github.com/louaySleman/react-native-launcher-kit/assets/89863936/37bab10c-af3b-4f91-8f9f-4fba5a58ca6f">

I am using React Native Expo

**Comment by louaySleman** [comment]
Hi @misharexviashvili,

Unfortunately, this package is designed exclusively for Android platforms and might not work as expected on other operating systems. We appreciate your interest and understand this might be disappointing. Please let us know if you have any other questions or if there's anything else we can assist you with related to Android development.

**Comment by misharexviashvili** [comment]
Yes, that's sad but understandable, on android it works really well, thanks.
